# ref: <https://github.com/oxsecurity/megalinter/blob/main/mega-linter-runner/generators/mega-linter-custom-flavor/templates/megalinter-custom-flavor-builder.yml>

name: Build & Push MegaLinter Custom Flavor

on:
  push:
    branches:
      - main
  release:
    types:
      - edited
      - published
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00, only on Sunday
  workflow_dispatch:
    inputs:
      megalinter-version:
        description: MegaLinter version to build (e.g., v7.5.0)
        required: false
        type: string
      is-latest:
        description: Mark this version as latest
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-custom-flavor:
    name: Build Custom MegaLinter Flavor
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - id: determine-tag
        name: Determine MegaLinter Version Tag
        run: |-
          case '${{ github.event_name }}' in
            'push')
              tag='beta'
              latest='false'
              ;;
            'release')
              tag='${{ github.ref_name }}'
              latest='true'
              ;;
            'schedule')
              tag='latest'
              latest='true'
              ;;
            'workflow_dispatch')
              tag='${{ inputs.megalinter-version }}'
              latest='${{ inputs.is-latest }}'
              ;;
          esac
          printf 'tag=%s\n' "$tag" >> "$GITHUB_OUTPUT"
          printf 'is-latest=%s\n' "$latest" >> "$GITHUB_OUTPUT"
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: login-dockerhub
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      - name: Build MegaLinter Custom Flavor
        uses: oxsecurity/megalinter/flavors/custom-builder@main
        with:
          megalinter-custom-flavor-builder-tag: ${{ steps.determine-tag.outputs.tag }}
          is-latest: ${{ steps.determine-tag.outputs.is-latest }}
          upload-to-ghcr: "true"
          upload-to-dockerhub: ${{ steps.login-dockerhub.outcome == 'success' && 'true' || 'false' }}
          dockerhub-repo: ${{ vars.DOCKERHUB_REPO }}
        env:
          CUSTOM_FLAVOR_BUILD_REPO_URL: ${{ github.repositoryUrl }}
          CUSTOM_FLAVOR_BUILD_REPO: ${{ github.repository }}
          CUSTOM_FLAVOR_BUILD_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
