# ref: <https://github.com/oxsecurity/megalinter/blob/main/mega-linter-runner/generators/mega-linter-custom-flavor/templates/megalinter-custom-flavor-builder.yml>

name: Build & Push MegaLinter Custom Flavor

on:
  push:
    branches:
      - main
  release:
    types:
      - edited
      - published
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00, only on Sunday
  workflow_dispatch:
    inputs:
      megalinter-version:
        description: MegaLinter version to build (e.g., v7.5.0)
        required: false
        type: string
      is-latest:
        description: Mark this version as latest
        required: false
        type: boolean
        default: false

env:
  TAG: beta
  LATEST: false

concurrency:
  group: ${{ github.workflow }} @ ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-custom-flavor:
    name: Build Custom MegaLinter Flavor
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - if: github.event_name == 'push'
        name: Determine MegaLinter Version Tag (push)
        run: |-
          printf 'TAG=%s\n' 'beta' >> "$GITHUB_ENV"
          printf 'LATEST=%s\n' 'false' >> "$GITHUB_ENV"
      - if: github.event_name == 'release'
        name: Determine MegaLinter Version Tag (release)
        run: |-
          printf 'TAG=%s\n' '${{ github.ref_name }}' >> "$GITHUB_ENV"
          printf 'LATEST=%s\n' 'true' >> "$GITHUB_ENV"
      - if: github.event_name == 'schedule'
        name: Determine MegaLinter Version Tag (schedule)
        run: |-
          printf 'TAG=%s\n' 'latest' >> "$GITHUB_ENV"
          printf 'LATEST=%s\n' 'true' >> "$GITHUB_ENV"
      - if: github.event_name == 'workflow_dispatch'
        name: Determine MegaLinter Version Tag (workflow_dispatch)
        run: |-
          printf 'TAG=%s\n' '${{ inputs.megalinter-version }}' >> "$GITHUB_ENV"
          printf 'LATEST=%s\n' '${{ inputs.is-latest }}' >> "$GITHUB_ENV"
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: login-dockerhub
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      - name: Build MegaLinter Custom Flavor
        uses: oxsecurity/megalinter/flavors/custom-builder@main
        with:
          megalinter-custom-flavor-builder-tag: ${{ env.TAG }}
          is-latest: ${{ env.LATEST }}
          upload-to-ghcr: "true"
          upload-to-dockerhub: ${{ steps.login-dockerhub.outcome == 'success' && 'true' || 'false' }}
          dockerhub-repo: ${{ vars.DOCKERHUB_REPO }}
        env:
          CUSTOM_FLAVOR_BUILD_REPO_URL: ${{ github.repositoryUrl }}
          CUSTOM_FLAVOR_BUILD_REPO: ${{ github.repository }}
          CUSTOM_FLAVOR_BUILD_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

  trigger-release:
    name: Trigger Releases
    needs:
      - build-custom-flavor
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Trigger Releases
        run: |-
          repository='liblaf/megalinter-custom-flavor-all'
          repo="$(cut --delimiter='/' --fields='2' <<< "$repository")"
          package_name="$repo/megalinter-custom-flavor"
          package_name="${package_name//'/'/'%2F'}"
          readarray -t tags < <(
            gh api \
              "/users/${{ github.repository_owner }}/packages/container/$package_name/versions" \
              --jq '.[].metadata.container.tags.[]' --paginate
          )
          for tag in "${tags[@]}"; do
            gh workflow run 'release.yaml' --field tag="$tag"
          done
